Sys.setlocale(,"UK_ua")
library(shiny)
library(openxlsx)
library(lattice)
library(readxl)
library(sp)
library(rhandsontable)
library(maptools)
library(ggplot2)
library(dplyr)
library(raster)
library(readxl)
library(rgeos)
library(rgdal)
library(maps)
library(geosphere)
library(plyr)
library(shinyTable)
library(mapproj)
library(colourpicker)
load("mapdata.RData")

#world.map <- readShapePoly("TM_WORLD_BORDERS_SIMPL-0.3.shp")
#
#world.map@data <- data.frame(readxl::read_excel("~/map_world/world_map.xlsx"))
#world.ggmap <- fortify(world.map, region = "NAME")
